apiVersion: apps/v1
kind: Deployment

metadata:
  name: aws-health-monitor

spec:
  replicas: 1

  selector:
    matchLabels:
      app: aws-health-monitor

  template:
    metadata:
      labels:
        app: aws-health-monitor

    spec:
      containers:
        - name: aws-health-monitor
          image: aws-health-monitor:v1
          imagePullPolicy: Never

          env:
            - name: AWS_DEFAULT_REGION
              value: us-east-1

          volumeMounts:
            - name: aws-credentials
              mountPath: /root/.aws
              readOnly: true

      volumes:
        - name: aws-credentials
          secret:
            secretName: aws-credentials