apiVersion: v1
kind: Pod

metadata:
  name: aws-health-monitor

spec:
  containers:
    - name: aws-health-monitor
      image: aws-health-monitor:v1
      imagePullPolicy: Never

      env:
        - name: AWS_DEFAULT_REGION
          value: us-east-1

      volumeMounts:
        - name: aws-credentials
          mountPath: /root/.aws
          readOnly: true

  volumes:
    - name: aws-credentials
      secret:
        secretName: aws-credentials